[package]
name = "pbsMetrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbs = { path = "../pbs" } 
clap = { version = "4.0", features=["derive"] }
serde_json = "1"
regex = "1"
